[package]
name = "fungible_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = '0x8a37ee8825095b05195fb680cb9b63b6de6f3cd0622d235f6588b63e8c81e87d'
initial_creator_addr = '0x8a37ee8825095b05195fb680cb9b63b6de6f3cd0622d235f6588b63e8c81e87d'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
